import { NextRequest, NextResponse } from 'next/server';

const VIBE_KANBAN_URL = process.env.VIBE_KANBAN_URL || 'http://localhost:62601';

const MOCK_AGENTS = [
  {
    id: 'maia',
    name: 'MAIA Orchestrator',
    capabilities: ['planning', 'meta', 'coding'],
    status: 'healthy',
    currentTasks: 2,
    maxTasks: 5,
    lastSeen: new Date().toISOString(),
    specialties: ['strategic planning', 'orchestration', 'meta-analysis'],
  },
  {
    id: 'sisyphus',
    name: 'Sisyphus PM',
    capabilities: ['planning', 'meta'],
    status: 'healthy',
    currentTasks: 1,
    maxTasks: 3,
    lastSeen: new Date().toISOString(),
    specialties: ['project management', 'task breakdown', 'scheduling'],
  },
  {
    id: 'coder',
    name: 'Coder Architect',
    capabilities: ['coding', 'testing', 'frontend', 'backend'],
    status: 'busy',
    currentTasks: 7,
    maxTasks: 10,
    lastSeen: new Date().toISOString(),
    specialties: ['architecture', 'implementation', 'refactoring'],
  },
  {
    id: 'ops',
    name: 'Ops Engineer',
    capabilities: ['infrastructure', 'devops', 'automation'],
    status: 'healthy',
    currentTasks: 1,
    maxTasks: 5,
    lastSeen: new Date().toISOString(),
    specialties: ['deployment', 'CI/CD', 'infrastructure'],
  },
  {
    id: 'researcher',
    name: 'Researcher Oracle',
    capabilities: ['research', 'meta'],
    status: 'idle',
    currentTasks: 0,
    maxTasks: 8,
    lastSeen: new Date().toISOString(),
    specialties: ['documentation', 'best practices', 'context research'],
  },
  {
    id: 'reviewer',
    name: 'Reviewer Gatekeeper',
    capabilities: ['review', 'testing'],
    status: 'healthy',
    currentTasks: 2,
    maxTasks: 6,
    lastSeen: new Date().toISOString(),
    specialties: ['code review', 'quality assurance', 'audit'],
  },
  {
    id: 'workflow',
    name: 'Workflow Automator',
    capabilities: ['automation', 'infrastructure'],
    status: 'idle',
    currentTasks: 0,
    maxTasks: 5,
    lastSeen: new Date().toISOString(),
    specialties: ['n8n', 'Flowise', 'automation workflows'],
  },
  {
    id: 'researcher_deep',
    name: 'Deep Oracle',
    capabilities: ['research', 'meta'],
    status: 'idle',
    currentTasks: 0,
    maxTasks: 5,
    lastSeen: new Date().toISOString(),
    specialties: ['academic research', 'thorough analysis', 'deep dive'],
  },
  {
    id: 'vision',
    name: 'Vision Analyst',
    capabilities: ['research', 'meta'],
    status: 'healthy',
    currentTasks: 1,
    maxTasks: 5,
    lastSeen: new Date().toISOString(),
    specialties: ['multimodal', 'image analysis', 'video analysis'],
  },
  {
    id: 'starter',
    name: 'Bootstrapper',
    capabilities: ['planning', 'infrastructure'],
    status: 'idle',
    currentTasks: 0,
    maxTasks: 5,
    lastSeen: new Date().toISOString(),
    specialties: ['project launch', 'bootstrap', 'init', 'setup'],
  },
  {
    id: 'librarian',
    name: 'Success Curator',
    capabilities: ['research', 'meta'],
    status: 'healthy',
    currentTasks: 1,
    maxTasks: 5,
    lastSeen: new Date().toISOString(),
    specialties: ['documentation', 'curation', 'knowledge vault', 'memory'],
  },
  {
    id: 'maia_premium',
    name: 'Supreme Arbiter',
    capabilities: ['meta', 'planning', 'review'],
    status: 'idle',
    currentTasks: 0,
    maxTasks: 3,
    lastSeen: new Date().toISOString(),
    specialties: ['escalation', 'paradox resolution', 'deadlock fix'],
  },
  {
    id: 'prometheus',
    name: 'Planner',
    capabilities: ['planning', 'meta'],
    status: 'healthy',
    currentTasks: 2,
    maxTasks: 5,
    lastSeen: new Date().toISOString(),
    specialties: ['milestones', 'decomposition', 'estimation'],
  },
  {
    id: 'oracle',
    name: 'Architect',
    capabilities: ['meta', 'planning', 'coding'],
    status: 'healthy',
    currentTasks: 1,
    maxTasks: 5,
    lastSeen: new Date().toISOString(),
    specialties: ['system mapping', 'risk assessment', 'complex debugging'],
  },
  {
    id: 'explore',
    name: 'Fast Scanner',
    capabilities: ['research'],
    status: 'healthy',
    currentTasks: 0,
    maxTasks: 10,
    lastSeen: new Date().toISOString(),
    specialties: ['scanning', 'codebase mapping', 'grep', 'glob'],
  },
  {
    id: 'frontend',
    name: 'UI Engineer',
    capabilities: ['frontend', 'coding'],
    status: 'idle',
    currentTasks: 0,
    maxTasks: 8,
    lastSeen: new Date().toISOString(),
    specialties: ['ui design', 'ux', 'responsive', 'animations', 'nextjs'],
  },
  {
    id: 'github',
    name: 'GitHub Expert',
    capabilities: ['automation', 'meta'],
    status: 'healthy',
    currentTasks: 1,
    maxTasks: 5,
    lastSeen: new Date().toISOString(),
    specialties: ['version control', 'git', 'collaboration', 'github actions'],
  },
  {
    id: 'sisyphus_junior',
    name: 'Code Executor',
    capabilities: ['coding'],
    status: 'busy',
    currentTasks: 8,
    maxTasks: 10,
    lastSeen: new Date().toISOString(),
    specialties: ['implementation', 'precision coding', 'diagnostics', 'task runner'],
  },
  {
    id: 'opencode',
    name: 'Platform Oracle',
    capabilities: ['meta', 'infrastructure'],
    status: 'healthy',
    currentTasks: 0,
    maxTasks: 5,
    lastSeen: new Date().toISOString(),
    specialties: ['ecosystem management', 'mcp integration', 'plugin audit'],
  },
];

export async function GET(request: NextRequest) {
  try {
    return NextResponse.json({
      success: true,
      data: MOCK_AGENTS,
    });
  } catch (error) {
    return NextResponse.json(
      {
        success: false,
        error: 'Failed to fetch agent data',
        error_data: error instanceof Error ? error.message : String(error),
      },
      { status: 500 }
    );
  }
}
