'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import { FileText, Download, Check } from 'lucide-react'
import Modal from './Modal'
import { jsPDF } from 'jspdf'

const formFields = [
  { id: 'fullName', label: 'Full Name', type: 'text', placeholder: 'John Doe' },
  { id: 'email', label: 'Email Address', type: 'email', placeholder: 'john@example.com' },
  { id: 'phone', label: 'Phone Number', type: 'tel', placeholder: '+1 (555) 123-4567' },
  { id: 'company', label: 'Company', type: 'text', placeholder: 'Acme Corporation' },
  { id: 'position', label: 'Position', type: 'text', placeholder: 'Senior Developer' },
]

export default function PdfDemo() {
  const [isOpen, setIsOpen] = useState(false)
  const [formData, setFormData] = useState<Record<string, string>>({})
  const [generated, setGenerated] = useState(false)

  const handleChange = (id: string, value: string) => {
    setFormData(prev => ({ ...prev, [id]: value }))
  }

  const handleGenerate = () => {
    setGenerated(true)
    setTimeout(() => setGenerated(false), 3000)
  }

  const handleDownloadPDF = () => {
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    const margin = 20
    let y = margin

    doc.setFillColor(26, 26, 46)
    doc.rect(0, 0, pageWidth, 20, 'F')

    doc.setFontSize(18)
    doc.setTextColor(255, 255, 255)
    doc.text('Application Form', margin, 13)

    y += 20

    doc.setDrawColor(255, 107, 53)
    doc.setLineWidth(0.5)
    doc.line(margin, y, pageWidth - margin, y)
    y += 15

    formFields.forEach((field, index) => {
      const value = formData[field.id] || ''

      doc.setFontSize(11)
      doc.setTextColor(255, 107, 53)
      doc.text(field.label, margin, y)

      doc.setFontSize(10)
      doc.setTextColor(200, 200, 200)
      doc.text(value || '[Not filled]', margin + 50, y)

      y += 10

      doc.setDrawColor(60, 60, 80)
      doc.setLineWidth(0.2)
      doc.line(margin, y, pageWidth - margin, y)
      y += 8

      if (index < formFields.length - 1 && y > 250) {
        doc.addPage()
        y = margin
      }
    })

    doc.setFontSize(10)
    doc.setTextColor(128, 128, 128)
    doc.text(`Generated by MAIA PDF Skill • ${new Date().toLocaleDateString()}`, margin, 280)

    doc.save('application-form.pdf')
  }

  const isFormComplete = formFields.every(field => formData[field.id]?.trim())

  return (
    <>
      <motion.div
        whileHover={{ y: -5 }}
        className="card-glass rounded-2xl p-6 transition-all hover:shadow-2xl hover:shadow-maia-secondary/20"
      >
        <div className="flex items-center gap-4 mb-4">
          <div className="p-3 bg-gradient-to-br from-maia-secondary to-blue-600 rounded-xl">
            <FileText className="w-8 h-8 text-white" />
          </div>
          <div>
            <h3 className="text-xl font-bold">PDF Form Filler</h3>
            <p className="text-white/60 text-sm">Generate professional PDF documents</p>
          </div>
        </div>
        <button
          onClick={() => setIsOpen(true)}
          className="btn-primary w-full flex items-center justify-center gap-2"
        >
          <FileText className="w-5 h-5" />
          Try It
        </button>
      </motion.div>

      <Modal isOpen={isOpen} onClose={() => setIsOpen(false)} title="PDF Form Generator">
        <div className="space-y-6">
          <div className="card-glass rounded-xl p-6">
            <h3 className="text-lg font-bold text-maia-accent mb-4">Application Information</h3>
            <div className="space-y-4">
              {formFields.map((field) => (
                <div key={field.id}>
                  <label className="block text-sm font-medium text-white/80 mb-2">
                    {field.label}
                  </label>
                  <input
                    type={field.type}
                    value={formData[field.id] || ''}
                    onChange={(e) => handleChange(field.id, e.target.value)}
                    placeholder={field.placeholder}
                    className="w-full bg-black/50 border border-white/20 rounded-lg px-4 py-3 focus:outline-none focus:border-maia-primary transition-colors"
                  />
                </div>
              ))}
            </div>
          </div>

          <div className="flex gap-3">
            <button
              onClick={handleGenerate}
              disabled={!isFormComplete}
              className="flex-1 btn-primary disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              {generated ? (
                <>
                  <Check className="w-5 h-5" />
                  Form Complete
                </>
              ) : (
                <>
                  <FileText className="w-5 h-5" />
                  Validate Form
                </>
              )}
            </button>
            <button
              onClick={handleDownloadPDF}
              disabled={!isFormComplete}
              className="flex-1 btn-secondary disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              <Download className="w-5 h-5" />
              Generate PDF
            </button>
          </div>

          <div className="card-glass rounded-xl p-4">
            <div className="flex items-center gap-3">
              <div className={`w-3 h-3 rounded-full ${isFormComplete ? 'bg-green-500' : 'bg-yellow-500'}`} />
              <span className="text-sm text-white/70">
                {isFormComplete
                  ? 'All fields completed — Ready to generate PDF'
                  : `${formFields.filter(f => formData[f.id]?.trim()).length} of ${formFields.length} fields filled`}
              </span>
            </div>
          </div>
        </div>
      </Modal>
    </>
  )
}
